# Generated by Django 4.2 on 2023-04-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('nominal_energy', models.FloatField()),
                ('nominal_autonomy', models.FloatField()),
                ('charging_power', models.FloatField()),
                ('charging_time', models.FloatField()),
                ('combustion_autonomy', models.FloatField(null=None)),
                ('tank_capacity', models.FloatField(null=None)),
            ],
            options={
                'verbose_name': 'Vehicle',
            },
        ),
    ]
