# Generated by Django 4.2 on 2023-04-21 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viability', '0002_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='combustion_autonomy',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tank_capacity',
            field=models.FloatField(null=True),
        ),
    ]
