# Generated by Django 4.2 on 2023-04-21 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viability', '0003_alter_vehicle_combustion_autonomy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='combustion_autonomy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='tank_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Eléctrico', 0), ('Híbrido', 1)], default=0, max_length=20),
        ),
    ]
