# Generated by Django 4.2 on 2023-04-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viability', '0004_alter_vehicle_combustion_autonomy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('Electric', 0), ('Hybrid', 1)], default=0, max_length=20),
        ),
    ]
